language: java
jdk: oraclejdk8
dist: trusty
script:
  - "mvn cobertura:cobertura"
  - jdk_switcher use oraclejdk8
  - mvn test


after_success:
  - bash <(curl -s https://codecov.io/bash) -t b4bb1364-dc4a-493f-b556-87d8ce7c63ac